pipeline {
    agent any

    tools {
        maven 'maven'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'master',
                url: 'https://github.com/ashwindhevaraj/seleniumplaywright.git'
            }
        }

        stage('Build') {
            steps {
                bat '''
                        cd seleniumplaywright
                        mvn clean test
                        '''
            }
        }

        stage('Run Tests') {
            steps {
                bat 'mvn test'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'target/**/*.html', allowEmptyArchive: true
        }
    }
}